.TH MYSTRNCPY 3 "September 2026" "MyUtils" "MyUtils Library"
.SH NAME
mystrncpy \- copy a limited number of characters from a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.PP
.B int mystrncpy(char *dest, const char *src, int n);
.SH DESCRIPTION
The
.B mystrncpy
function copies up to
.B n
characters from the string
.B src
to the destination string
.B dest .
If the source string is shorter than
.B n
characters, the remaining positions are filled with null characters.
.SH RETURN VALUE
Returns the number of positions processed.
.SH AUTHOR
Iman Amir <emanhamza234467@gmail.com>
