.TH MYSTRCPY 3 "September 2026" "MyUtils" "MyUtils Library"
.SH NAME
mystrcpy \- copy a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.PP
.B int mystrcpy(char *dest, const char *src);
.SH DESCRIPTION
The
.B mystrcpy
function copies the string
.B src
into the destination string
.B dest ,
including the terminating null character.
.SH RETURN VALUE
Returns the number of characters copied, not including the terminating null character.
.SH AUTHOR
Iman Amir <emanhamza234467@gmail.com>
